### ISSUE TITLE
How to convert 3D UMAP plots to 3D scHex plots?

### ISSUE THREAD

**Issue by davisidarta** [SaskiaFreytag/schex#7]
Hi, I wonder if its possible to use schex to 3D UMAP plots.

Best,
Davi

**Comment by SaskiaFreytag** [comment]
Hi Davi,

So after some research it turns out that this is not a trivial problem. First of all one would have to change the hexagon to a 3d shape with the same properties as the hexagon has in 2d space. Probably the best solution would be the rhombic dodecahedron. There are however no  simple implementations of plotting such shapes in R. Since I am not a big fan of 3d plots myself and for [good reasons](https://serialmentor.com/dataviz/no-3d.html), I am simply not willing to invest the time. (Sorry)

Cheers,

Saskia
